### PR TITLE
Finished for-loop section in tutorial

### PR DESCRIPTION
**Pull request by duckmopsi**
For some reason the correction in error.ts is still shown.
Creating the pull request, so that I am able to rebase.

### CODE REVIEW

**Comment by Jartreg** [comment]
I'm not sure how creating a PR helps you fixing something locally, but I'm guessing the issue might come from how you are interacting with the repository. 
When working on something, you should create a new branch for your work. Working directly on the master branch leads to these kinds of issues (I'm guessing you're working on `master`? Correct me if I'm wrong).

Because @TGlas modified your commits during the merge (by "squashing" them), the `master`-branch you are working with is no longer compatible with `master` on GitHub. This wouldn't be a problem if you were working with individual branches:
Since you are not on master, you can simply switch back, pull, and create a new branch for work. The branch you worked on is no longer relevant because the work is merged (= completed).

### "No longer compatible"?
If you take a look at [your previous PR](https://github.com/TGlas/tscript/pull/90), the commit you wanted to merge is 69b790b. However, the commit @TGlas merged (by squashing) is 7972b09. If you search the history on GitHub, you will only find the commit @TGlas merged, not the one you uploaded. This means, that while GitHub might know that your PR is merged, git does not. Continuing to work off of this commit will inevitably lead to these issues, because while your changes are already included in the "official" `master`-branch, your local repository simply doesn't know about it.

**Comment by duckmopsi** [comment]
I needed to commit to be able to rebase my branch and pull updates from Master.

I forked the repository and work on that fork. I have not created any branches, since I thought the fork itself would work as this safery measure. Do I understand correctly that working this way with branches would have the same effect as always creating a new fork for every bit of work?

Is it possible to merge the changes from this pull request? I'd then continue working on a new branch.

**Comment by TGlas** [comment]
Can you run `npm run prettier` and commit + push again? That should update the PR and fix the failing check.

**Comment by duckmopsi** [comment]
I just did. I'll open a new branch now.

**Review by TGlas — COMMENTED** [review]
Viewing the changes, I am a bit irritated. First of all, they seem to duplicate PR #93. For some reason, the pre-#93 state seems to be used by github as a basis for displaying changes. That does not make any sense to me.

Also, I cannot find any actual extension of the tutorial text, aside from minor fixes introduced by myself weeks ago. Are you sure that publishing the PR worked as intended?

**Comment by duckmopsi** [comment]
> 
> 
> Viewing the changes, I am a bit irritated. First of all, they seem to duplicate PR #93. For some reason, the pre-#93 state seems to be used by github as a basis for displaying changes. That does not make any sense to me.
> 
> Also, I cannot find any actual extension of the tutorial text, aside from minor fixes introduced by myself weeks ago. Are you sure that publishing the PR worked as intended?

I did not do any PR manually.. This might be the result of my merging between origin/master and upstream/master? I just followed stackoverflow tutorials to do so.

**Comment by Jartreg** [comment]
This PR was abandoned when @duckmopsi created #92 it was just forgotten to be closed.

**Comment by TGlas** [comment]
Thanks, that explains it. Weird... I got a message about it less than 2 hours ago. Anyway, fine.
@duckmopsi: Please close the PR if you don't update it any more.

**Pull request closed without merging**
