### PR TITLE
Additional String functions

### PR DESCRIPTION
**Pull request by TheRealFloatDev**
I also noticed that the String type is lacking some basic functionality, more precise I added:

- toLowerCase()
- toUpperCase()
- replace()

All functions are also added in the docs

### CODE REVIEW

**Comment by TGlas** [comment]
Thanks, that's really useful. However, please disallow regular expressions in "replace" to make the method more beginner friendly.

**Comment by TheRealFloatDev** [comment]
I have now removed regex support from the function.

**Comment by TGlas** [comment]
Thanks! One more small thing: Please run `npm run prettier` before to make the checks succeed.

**Comment by TGlas** [comment]
Thanks a lot.

**Pull request merged**
