### PR TITLE
fix path sanitization

### PR DESCRIPTION
**Pull request by Freax13**
#110 reintroduced the XSS vulnerability fixed by #108. `showPage` must also sanitize the path that is passed on internally, not only the user visible URL.

@Jartreg Can you verify that this pr doesn't break anything?

### CODE REVIEW

**Review by Jartreg — CHANGES_REQUESTED** [review]
How about we approach this differently... I don't think it's a bug that should be fixed here in `index.ts` since its duty should basically just be to pass on url parameters.

I'd rather suggest that we sanitize the tokens when they are displayed:
https://github.com/TGlas/tscript/blob/f34a088587a51e4a4cd84fdf1f6153aa4adecbb3/src/ide/doc.ts#L672-L675

Escaping characters like `<`, `>` and `&` in `key[i]` before adding it to `html` should resolve this issue at the root. _Ideally_ we'd use `Text` nodes to avoid having to deal with sanitization altogether, but that would require too much refactoring.

What do you think?

**Comment by Freax13** [comment]
Fair enough, we could reuse the escape function already in the code base: https://github.com/TGlas/tscript/blob/f34a088587a51e4a4cd84fdf1f6153aa4adecbb3/src/eval/index.ts#L138-L150

I'd like to note that JavaScript already has a (deprecated) function called `escape` used for escaping url queries and that function is also used within the code base: https://github.com/TGlas/tscript/blob/f34a088587a51e4a4cd84fdf1f6153aa4adecbb3/src/ide/ide.ts#L1151

So if we pull the function out of `eval/index.ts` and reuse it in `ide/doc.ts`, I'd like to suggest renaming the function eg. to `escapeHtmlChars` to avoid confusion between JavaScript's `escape` and our `escape`.

**Comment by TGlas** [comment]
Good point. I imported the code in `eval/index.ts` from a different source without putting too much effort into making it consistent with the rest. Feel free to rename and move the function around.

**Comment by TGlas** [comment]
Thanks, looks good!

**Pull request merged**
