### PR TITLE
fixed bug 85

### PR DESCRIPTION
**Pull request by duckmopsi**
Github didn't let me create a new PR at first which is why I made an extra commit without any change (1 space) to see if that fixes it and it kinda did.

### CODE REVIEW

**Review by Jartreg — CHANGES_REQUESTED** [review]
* The changes in `ide.ts`, `package.json` and `package-lock.json` are completely unrelated. I would suggest you create a separate PR for that.
* You need to `npm run prettier`

**Comment by Jartreg** [comment]
> Github didn't let me create a new PR
It didn't let you create a new one because you _already had_ an open PR for that. If you push commits to a branch with an open PR, they will be part of that PR. In this case, you didn't have to close #88. If you take a look at #88, it also contains your new commits.

**Comment by duckmopsi** [comment]
> 
> 
>     * The changes in `ide.ts`, `package.json` and `package-lock.json` are completely unrelated. I would suggest you create a separate PR for that.
> 
>     * You need to `npm run prettier`

That was a mistake, is there a possibility to reset to two pushes before?

**Comment by Jartreg** [comment]
You _could_ do an interactive rebase and force push the new branch, but that might be too complicated and I currently can't write a more detailed description.

An easier solution might be that you commit these files as they were before and @TGlas squashes the commits when merging.

**Comment by Jartreg** [comment]
Okay, here on how to do the rebase:

1. Run `git rebase -i master` → an editor will open
2. Replace `pick 25c3670 fixed error 35` with `edit 25c3670 fixed error 35`
3. Save and close the editor
4. Change the files in question
5. Stage them and commit them using `git commit --amend`
6. Finish the rebase using `git rebase --continue`
7. Force push the changes using `git push --force`

<details>
<summary>
If anything doesn't go as expected</summary>

* `git rebase --abort`
* `git reset --hard 021fb4cb`

</details>

**Comment by duckmopsi** [comment]
> 
> 
> Okay, here on how to do the rebase:
> 
>     1. Run `git rebase -i master` → an editor will open
> 
>     2. Replace as follows:
>        ```diff
>        pick b44a27f finally fixing the example error
>        -pick 25c3670 fixed error 35
>        +edit 25c3670 fixed error 35
>        pick 021fb4c test to see why PR doesn't work
>        ```
> 
>     3. Save and close the editor
> 
>     4. Change the files in question
> 
>     5. Stage them and commit them using `git commit --amend`
> 
>     6. Finish the rebase using `git rebase --continue`
> 
>     7. Force push the changes using `git push --force`
> 
> 
> If anything doesn't go as expected

Thanks for the in-depth guide but I do have the problem that I cannot do anything in the editor that opens. I guess that might have something to do with me working on windows. 
error

Pressing any key doesn't have any impact.

Wouldn't it be the best for me to delete the fork (again), create a new one, only change error.ts, create a new pull request and then update npm? I won't commit any changes to npm then but I need to update it to work on my system. Then I could focus on working on the tutorial and then also only push the files I am working on.

**Comment by Jartreg** [comment]
Oops, you might need to do `git rebase -i 9f3dee15`. And to edit you might need to press `i`.

**Comment by Jartreg** [comment]
> Wouldn't it be the best for me to delete the fork (again), create a new one, only change error.ts, create a new pull request and then update npm? I won't commit any changes to npm then but I need to update it to work on my system. Then I could focus on working on the tutorial and then also only push the files I am working on.

Yeah that might be the best idea... Although you can already update npm, just don't commit `package-lock.json` and `package.json`. Since you specify which files you want to commit, you would just have to _not_ add them.

And you don't need to delete your fork, running this should put you back on the same state as the current master branch:

```sh
git reset --hard 9f3dee15
git push --force
```

**Comment by duckmopsi** [comment]
> 
> 
> > Wouldn't it be the best for me to delete the fork (again), create a new one, only change error.ts, create a new pull request and then update npm? I won't commit any changes to npm then but I need to update it to work on my system. Then I could focus on working on the tutorial and then also only push the files I am working on.
> 
> Yeah that might be the best idea... Although you can already update npm, just don't commit `package-lock.json` and `package.json`. Since you specify which files you want to commit, you would just have to _not_ add them.
> 
> And you don't need to delete your fork, running this should put you back on the same state as the current master branch:
> 
> ```shell
> git reset --hard 9f3dee15
> git push --force
> ```

I will do that then, since rn I'm not even able to get out of the editor. Using ":qa" as a command leads to E37 and E162 as errors and I don't really know what's even the problem.

I'll reset everything, change the error.ts and then work on the tutorial. Thank you for your help.

**Comment by Jartreg** [comment]
Muahahahaha! 😈 It looks like you, like millions before, have fallen victim to the [devious trap of vim](https://stackoverflow.blog/2017/05/23/stack-overflow-helping-one-million-developers-exit-vim/)... Next time maybe `:q!` will help.

**Comment by duckmopsi** [comment]
Thank you, I'm not too familiar with vim! :)

**Pull request closed without merging**
